apiVersion: v1
kind: Service
metadata:
  name: node-js-server-prod
  namespace: prod
spec:
  selector:
    app: node-js-server-prod
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
