apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-server-stage
  labels:
    app: registry.devopsnow.io/internal/node-js-server:opsverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-server-stage
  template:
    metadata:
      labels:
        app: node-js-server-stage
    spec:
      containers:
        - name: node-js-server-stage
          image: registry.devopsnow.io/internal/node-js-server:d676c0b2
          ports:
            - containerPort: 3000
